import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/Navbar";
import Tabs from "../components/Tabs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bookmark Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <header>
        <NavBar />
        <div className="md:w-5/6 grid md:grid-cols-2 grid-cols-1 mx-auto md:mt-0 gap-y-10">
          <div className="md:col-span-1 py-16 px-5 md:px-10 order-last md:order-first md:text-left text-center">
            <h2 className="font-bold text-3xl md:text-4xl">
              A Simple Bookmark Manager
            </h2>
            <p className="text-grayishBlue text-lg mt-4 mb-4">
              A clean and simple interface to organize your favourite websites.
              Open a new browser tab and see your sites load instantly. Try it
              for free.
            </p>
            <button className="text-white text-sm bg-softBlue px-3 py-2 mr-3">
              Get it on Chrome
            </button>
            <button className="px-3 py-2 bg-white text-sm text-black shadow-lg">
              Get it on Firefox
            </button>
          </div>
          <div className="md:col-span-1 flex items-end relative">
            <div className="md:absolute right-0 bottom-0 md:translate-x-1/2 translate-y-1/3 bg-softBlue ml-32 md:ml-0 w-full h-44 md:h-72 rounded-l-full">
              <img
                src="/images/illustration-hero.svg"
                className="absolute transform scale-150 md:scale-100 bottom-10 left-1/2 md:left-0 -translate-x-3/4 md:-translate-x-1/2"
                alt=""
              />
            </div>
          </div>
        </div>
      </header>
      <main>
        <section id="features" className="text-center mt-20 px-2">
          <h2 className="text-3xl font-bold">Features</h2>
          <p className="text-lg text-grayishBlue md:px-96 mt-4">
            Our aim is to make it quick and easy for you to access your
            favourite websites. Your bookmarks sync between your devices so you
            can access them on the go.
          </p>
          <Tabs />
        </section>
        <section id="pricing" className="text-center mt-40 px-2">
          <div className="md:px-20 md:w-1/2 w-5/6 mx-auto">
            <h2 className="md:text-3xl text-2xl font-bold">
              Download the extension
            </h2>
            <p className="mt-4 text-grayishBlue">
              We’ve got more browsers in the pipeline. Please do let us know if
              you’ve got a favourite you’d like us to prioritize.
            </p>
          </div>
        </section>
      </main>

      <footer></footer>
    </div>
  );
}
