import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import ContactInput from "../components/ContactInput";
import NavBar from "../components/Navbar";
import Tabs from "../components/Tabs";

export default function Home() {
  const [faq, setFaq] = useState([
    {
      id: "answer1",
      question: "What is Bookmark?",
      show: false,
      answer:
        "Loremipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt justo egetultricies fringilla. Phasellus blandit ipsum quis quam ornare mattis.Loremipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt justo egetultricies fringilla. Phasellus blandit ipsum quis quam ornare mattis.Loremipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt justo egetultricies fringilla. Phasellus blandit ipsum quis quam ornare mattis.",
    },
    {
      id: "answer2",
      question: "How can I request a new browser?",
      show: false,
      answer:
        "Loremipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt justo egetultricies fringilla. Phasellus blandit ipsum quis quam ornare mattis.",
    },
    {
      id: "answer3",
      question: "Is there a mobile app?",
      show: false,
      answer:
        "Loremipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt justo egetultricies fringilla. Phasellus blandit ipsum quis quam ornare mattis.",
    },
    {
      id: "answer4",
      question: "What about other Chromium browsers?",
      show: false,
      answer:
        "Loremipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt justo egetultricies fringilla. Phasellus blandit ipsum quis quam ornare mattis.",
    },
  ]);

  return (
    <div>
      <Head>
        <title>Bookmark Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <header>
        <NavBar />
        <div className="md:w-5/6 grid md:grid-cols-2 grid-cols-1 mx-auto md:mt-0 gap-y-10">
          <div className="md:col-span-1 py-16 px-5 md:px-10 order-last md:order-first md:text-left text-center">
            <h2 className="font-bold text-3xl md:text-4xl">
              A Simple Bookmark Manager
            </h2>
            <p className="text-grayishBlue text-lg mt-4 mb-4">
              A clean and simple interface to organize your favourite websites.
              Open a new browser tab and see your sites load instantly. Try it
              for free.
            </p>
            <button className="text-white text-sm bg-softBlue px-3 py-2 mr-3">
              Get it on Chrome
            </button>
            <button className="px-3 py-2 bg-white text-sm text-black shadow-lg">
              Get it on Firefox
            </button>
          </div>
          <div className="md:col-span-1 flex items-end relative">
            <div className="md:absolute right-0 bottom-0 md:translate-x-1/2 translate-y-1/3 bg-softBlue ml-32 md:ml-0 w-full h-44 md:h-72 rounded-l-full">
              <img
                src="/images/illustration-hero.svg"
                className="absolute transform scale-150 md:scale-100 bottom-10 left-1/2 md:left-0 -translate-x-3/4 md:-translate-x-1/2"
                alt=""
              />
            </div>
          </div>
        </div>
      </header>
      <main>
        <section id="features" className="text-center mt-20 px-2">
          <h2 className="text-3xl font-bold">Features</h2>
          <p className="text-lg text-grayishBlue md:px-96 mt-4">
            Our aim is to make it quick and easy for you to access your
            favourite websites. Your bookmarks sync between your devices so you
            can access them on the go.
          </p>
          <Tabs />
        </section>
        <section id="pricing" className="text-center mt-40 px-2">
          <div className="md:px-20 md:w-1/2 w-5/6 mx-auto">
            <h2 className="md:text-3xl text-2xl font-bold">
              Download the extension
            </h2>
            <p className="mt-4 text-grayishBlue">
              We’ve got more browsers in the pipeline. Please do let us know if
              you’ve got a favourite you’d like us to prioritize.
            </p>
          </div>
          <div className="grid w-2/3 md:grid-cols-3 grid-cols-1 mx-auto mt-7 gap-x-8 gap-y-10">
            <div className="col-span-1 grid grid-cols-1 items-center shadow-xl">
              <div className="col-span-1 border-b-2 border-dashed py-10">
                <Image width={100} height={100} src="/images/logo-chrome.svg" />
                <h3 className="font-bold text-xl mt-4">Add to Chrome</h3>
                <p className="text-sm text-grayishBlue">Minimum version 62</p>
              </div>
              <div className="my-4">
                <button className="w-5/6 bg-softBlue border-2 border-softBlue text-white hover:text-softBlue hover:bg-white rounded py-2">
                  {"Add & Install Extension"}
                </button>
              </div>
            </div>
            <div className="col-span-1 grid grid-cols-1 items-center shadow-xl relative md:top-10">
              <div className="col-span-1 border-b-2 border-dashed py-10">
                <Image
                  width={100}
                  height={100}
                  src="/images/logo-firefox.svg"
                />
                <h3 className="font-bold text-xl mt-4">Add to Firefox</h3>
                <p className="text-sm text-grayishBlue">Minimum version 55</p>
              </div>
              <div className="my-4">
                <button className="w-5/6 bg-softBlue border-2 border-softBlue text-white hover:text-softBlue hover:bg-white rounded py-2">
                  {"Add & Install Extension"}
                </button>
              </div>
            </div>
            <div className="col-span-1 grid grid-cols-1 items-center shadow-xl relative md:top-20">
              <div className="col-span-1 border-b-2 border-dashed py-10">
                <Image width={100} height={100} src="/images/logo-opera.svg" />
                <h3 className="font-bold text-xl mt-4">Add to Chrome</h3>
                <p className="text-sm text-grayishBlue">Minimum version 62</p>
              </div>
              <div className="my-4">
                <button className="w-5/6 bg-softBlue border-2 border-softBlue text-white hover:text-softBlue hover:bg-white rounded py-2">
                  {"Add & Install Extension"}
                </button>
              </div>
            </div>
          </div>
        </section>
        <div className="md:w-1/2 mx-auto mt-20 pt-20">
          <h2 className="text-3xl text-center font-bold">
            Frequently Asked Questions
          </h2>
          <p className="text-grayishBlue font-lg text-center md:px-28 px-4 mt-4">
            Here are some of our FAQs. If you have any other questions you’d
            like answered please feel free to email us.
          </p>
          <ul className="mt-10">
            {faq.map((item) => (
              <li className="p-4 border-y" id={item.id} key={item.id}>
                <div className="cursor-pointer hover:text-softRed flex justify-between items-center">
                  <p>{item.question}</p>
                  <Image
                    src="/images/icon-arrow.svg"
                    className={
                      item.show
                        ? "transition-transform rotate-180 duration-500"
                        : "transition-transform duration-500 rotate-0"
                    }
                    width={20}
                    height={15}
                    onClick={() => {
                      const newFaq = faq.map((i) => {
                        if (i.id === item.id) {
                          i.show = !i.show;
                        }
                        return i;
                      });
                      setFaq(newFaq);
                    }}
                  />
                </div>
                <div
                  className={
                    item.show
                      ? "mt-5 transition-all h-auto duration-500"
                      : "mt-5 transition-all h-0 duration-500 overflow-hidden hidden"
                  }
                >
                  <p className="text-lg text-grayishBlue">{item.answer}</p>
                </div>
              </li>
            ))}
          </ul>
          <div className="flex justify-center mt-10">
            <button className="px-4 py-2 bg-softBlue text-white rounded">
              More Info
            </button>
          </div>
        </div>
        <section
          id="contact"
          className="flex flex-col justify-center bg-softBlue p-10 mt-20 md:mt-40"
        >
          <div className="md:w-1/2 mx-auto">
            <h4 className="text-center text-lg text-white uppercase">
              35,000 + already joined
            </h4>
            <h2 className="text-white text-2xl text-center md:px-28 mt-5">
              Stay up-to-date with what we are doing
            </h2>
            <ContactInput />
          </div>
        </section>
      </main>

      <footer className="bg-veryDarkBlue p-7">
        <div className="w-5/6 mx-auto flex md:flex-row flex-col items-center md:justify-between">
          <div className="flex md:justify-between md:flex-row flex-col md:mt-0 md:w-1/2">
            <svg width="148" height="25" xmlns="http://www.w3.org/2000/svg">
              <g fill="none" fillRule="evenodd">
                <path
                  d="M37 6.299h5.227c.746 0 1.434.155 2.062.466.629.311 1.123.735 1.484 1.27s.542 1.12.542 1.754c0 .672-.165 1.254-.495 1.746-.33.491-.762.868-1.297 1.129v.15c.697.248 1.25.643 1.661 1.185.41.541.616 1.191.616 1.95 0 .735-.196 1.385-.588 1.951a3.817 3.817 0 0 1-1.587 1.307c-.665.305-1.403.457-2.212.457H37V6.299zm5.04 5.45c.548 0 .986-.152 1.316-.457.33-.305.495-.688.495-1.148 0-.448-.159-.824-.476-1.13-.318-.304-.738-.457-1.26-.457H39.52v3.192h2.52zm.28 5.619c.61 0 1.086-.159 1.428-.476.342-.317.513-.731.513-1.241 0-.51-.174-.927-.522-1.251-.349-.324-.847-.485-1.494-.485H39.52v3.453h2.8zm12.927 2.595c-1.307 0-2.492-.308-3.556-.924a6.711 6.711 0 0 1-2.511-2.53c-.61-1.07-.915-2.246-.915-3.528 0-1.281.305-2.457.915-3.528a6.711 6.711 0 0 1 2.51-2.529C52.756 6.308 53.94 6 55.248 6c1.306 0 2.492.308 3.556.924a6.711 6.711 0 0 1 2.51 2.53c.61 1.07.915 2.246.915 3.527 0 1.282-.305 2.458-.915 3.528a6.711 6.711 0 0 1-2.51 2.53c-1.064.616-2.25.924-3.556.924zm0-2.39a4.52 4.52 0 0 0 2.258-.578 4.177 4.177 0 0 0 1.615-1.624c.392-.697.588-1.494.588-2.39 0-.896-.196-1.692-.588-2.389a4.177 4.177 0 0 0-1.615-1.624 4.52 4.52 0 0 0-2.258-.579 4.47 4.47 0 0 0-2.25.579 4.195 4.195 0 0 0-1.605 1.624c-.392.697-.588 1.493-.588 2.39 0 .895.196 1.692.588 2.389a4.195 4.195 0 0 0 1.605 1.624 4.47 4.47 0 0 0 2.25.578zm15.353 2.39c-1.307 0-2.492-.308-3.556-.924a6.711 6.711 0 0 1-2.51-2.53c-.61-1.07-.915-2.246-.915-3.528 0-1.281.305-2.457.914-3.528a6.711 6.711 0 0 1 2.511-2.529C68.108 6.308 69.294 6 70.6 6c1.307 0 2.492.308 3.556.924a6.711 6.711 0 0 1 2.51 2.53c.61 1.07.915 2.246.915 3.527 0 1.282-.305 2.458-.914 3.528a6.711 6.711 0 0 1-2.511 2.53c-1.064.616-2.25.924-3.556.924zm0-2.39a4.52 4.52 0 0 0 2.259-.578 4.177 4.177 0 0 0 1.614-1.624c.392-.697.588-1.494.588-2.39 0-.896-.196-1.692-.588-2.389a4.177 4.177 0 0 0-1.614-1.624 4.52 4.52 0 0 0-2.259-.579 4.47 4.47 0 0 0-2.25.579 4.195 4.195 0 0 0-1.605 1.624c-.392.697-.588 1.493-.588 2.39 0 .895.196 1.692.588 2.389a4.195 4.195 0 0 0 1.606 1.624 4.47 4.47 0 0 0 2.249.578zM79.83 6.3h2.52v5.73h.15l4.89-5.73h3.043v.149L85.6 11.973l5.338 7.542v.149h-3.08l-3.994-5.693-1.512 1.773v3.92h-2.52V6.299zM93.779 6h3.248l3.546 9.39h.15L104.268 6h3.267v13.365h-2.501v-6.589l.15-2.221h-.15l-3.398 8.81h-1.96l-3.416-8.81h-.149l.15 2.221v6.59h-2.483V6zm20.8 0h2.894l5.021 13.365h-2.781l-1.12-3.192h-5.115l-1.12 3.192h-2.781L114.579 6zm3.193 7.859l-1.176-3.36-.486-1.606h-.149l-.485 1.606-1.195 3.36h3.49zM124.553 6h4.872c.871 0 1.646.18 2.324.541.678.361 1.204.862 1.577 1.503.374.64.56 1.366.56 2.175 0 .858-.27 1.62-.812 2.286a4.617 4.617 0 0 1-2.044 1.447l-.018.13 3.584 5.134v.15h-2.894l-3.453-5.022h-1.176v5.021h-2.52V6zm4.853 6.03c.573 0 1.04-.175 1.4-.523.361-.349.542-.79.542-1.326 0-.51-.172-.945-.514-1.306-.342-.361-.806-.542-1.39-.542h-2.371v3.696h2.333zm7.23-6.03h2.52v5.73h.15l4.89-5.73h3.043v.15l-4.835 5.525 5.34 7.541v.15h-3.08l-3.996-5.694-1.512 1.773v3.92h-2.52V6z"
                  fill="#fff"
                  fillRule="nonzero"
                />
                <g>
                  <circle fill="#5267DF" cx="12.5" cy="12.5" r="12.5" />
                  <path
                    d="M9 9v10l3.54-3.44L16.078 19V9a2 2 0 0 0-2-2H11a2 2 0 0 0-2 2z"
                    fill="#FFF"
                  />
                </g>
              </g>
            </svg>
            <ul className="uppercase mt-4 md:mt-0 flex flex-col text-center md:text-start md:flex-row text-grayishBlue justify-center md:justify-between md:w-1/2">
              <li className="">FEATURES</li>
              <li className=" md:mt-0 md:">PRICING</li>
              <li className=" md:mt-0 md:">CONTACT</li>
            </ul>
          </div>
          <div className="flex md:items-center mt-4">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              className="mr-7 fill-white hover:fill-softRed cursor-pointer"
              height="24"
            >
              <path
                fillRule="evenodd"
                d="M22.675 0H1.325C.593 0 0 .593 0 1.325v21.351C0 23.407.593 24 1.325 24H12.82v-9.294H9.692v-3.622h3.128V8.413c0-3.1 1.893-4.788 4.659-4.788 1.325 0 2.463.099 2.795.143v3.24l-1.918.001c-1.504 0-1.795.715-1.795 1.763v2.313h3.587l-.467 3.622h-3.12V24h6.116c.73 0 1.323-.593 1.323-1.325V1.325C24 .593 23.407 0 22.675 0z"
              />
            </svg>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="fill-white hover:fill-softRed cursor-pointer"
              width="24"
              height="20"
            >
              <path
                fillRule="evenodd"
                d="M24 2.557a9.83 9.83 0 0 1-2.828.775A4.932 4.932 0 0 0 23.337.608a9.864 9.864 0 0 1-3.127 1.195A4.916 4.916 0 0 0 16.616.248c-3.179 0-5.515 2.966-4.797 6.045A13.978 13.978 0 0 1 1.671 1.149a4.93 4.93 0 0 0 1.523 6.574 4.903 4.903 0 0 1-2.229-.616c-.054 2.281 1.581 4.415 3.949 4.89a4.935 4.935 0 0 1-2.224.084 4.928 4.928 0 0 0 4.6 3.419A9.9 9.9 0 0 1 0 17.54a13.94 13.94 0 0 0 7.548 2.212c9.142 0 14.307-7.721 13.995-14.646A10.025 10.025 0 0 0 24 2.557z"
              />
            </svg>
          </div>
        </div>
      </footer>
    </div>
  );
}
